<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\EventListener\GalleryImageListener' shared autowired service.

include_once $this->targetDirs[3].'/src/EventListener/GalleryImageListener.php';

return $this->services['App\EventListener\GalleryImageListener'] = new \App\EventListener\GalleryImageListener(($this->targetDirs[3].'/public/uploads/gallery_images'));
