<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.J1QHskN.App\Entity\PreviousQuiz' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.J1QHskN": it references class "App\\Entity\\PreviousQuiz" but no such service exists.');
