<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\EventListener\PreviousQuizListener' shared autowired service.

include_once $this->targetDirs[3].'/src/EventListener/PreviousQuizListener.php';

return $this->services['App\EventListener\PreviousQuizListener'] = new \App\EventListener\PreviousQuizListener(($this->targetDirs[3].'/public/uploads/previous_quiz'));
