<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Ks9o1Ek' shared service.

return $this->privates['.service_locator.Ks9o1Ek'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('image' => function (): \App\Entity\GalleryImage {
    return ($this->privates['.errored..service_locator.Ks9o1Ek.App\Entity\GalleryImage'] ?? $this->load('getGalleryImageService.php'));
}));
