<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.RQ2iiYW' shared service.

return $this->privates['.service_locator.RQ2iiYW'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('img_uploader' => function (): \App\Service\GalleryImageUploader {
    return ($this->privates['App\Service\GalleryImageUploader'] ?? $this->privates['App\Service\GalleryImageUploader'] = new \App\Service\GalleryImageUploader(($this->targetDirs[3].'/public/uploads/gallery_images')));
}, 'quiz_uploader' => function (): \App\Service\PreviousQuizUploader {
    return ($this->privates['App\Service\PreviousQuizUploader'] ?? $this->privates['App\Service\PreviousQuizUploader'] = new \App\Service\PreviousQuizUploader(($this->targetDirs[3].'/public/uploads/previous_quiz')));
}));
