<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.uH.2OTH.App\Entity\TrainingQuiz' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.uH.2OTH": it references class "App\\Entity\\TrainingQuiz" but no such service exists.');
