<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\AnswerImageUploader' shared autowired service.

include_once $this->targetDirs[3].'/src/Service/AnswerImageUploader.php';

return $this->privates['App\Service\AnswerImageUploader'] = new \App\Service\AnswerImageUploader(($this->targetDirs[3].'/public/uploads/answer_images'));
