<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\EventListener\TrainingQuestionListener' shared autowired service.

include_once $this->targetDirs[3].'/src/EventListener/TrainingQuestionListener.php';

return $this->services['App\EventListener\TrainingQuestionListener'] = new \App\EventListener\TrainingQuestionListener(($this->targetDirs[3].'/public/uploads/question_images'));
