<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container08KdSJe\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container08KdSJe/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container08KdSJe.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container08KdSJe\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container08KdSJe\srcDevDebugProjectContainer(array(
    'container.build_hash' => '08KdSJe',
    'container.build_id' => '15fa24e5',
    'container.build_time' => 1531316608,
), __DIR__.\DIRECTORY_SEPARATOR.'Container08KdSJe');
