<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGT2h1Ca\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGT2h1Ca/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGT2h1Ca.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGT2h1Ca\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerGT2h1Ca\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'GT2h1Ca',
    'container.build_id' => 'a820e3a3',
    'container.build_time' => 1535115364,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerGT2h1Ca');
