<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ0r2Jf4\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ0r2Jf4/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJ0r2Jf4.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJ0r2Jf4\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerJ0r2Jf4\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'J0r2Jf4',
    'container.build_id' => '00040d98',
    'container.build_time' => 1534845605,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ0r2Jf4');
